---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
server:
  port: 0
---
spring:
  profiles: sentence
server:  
  port: 8020
words: NA  
---
spring:
  profiles: sujeto
words: I,You,He,She,It
---
spring:
  profiles: verbo
words: play, sing, scream, dance, discover
