---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 0
---
spring:
  profiles: sentence
server:  
  port: 8020
words: NA  
---
spring:
  profiles: development
server:  
  port: 8030
---
spring:
  profiles: development_A
server:  
  port: 8040
---
spring:
  profiles: sujeto
words: I,You,He,She,It
---
spring:
  profiles: verbo
words: play, sing, scream, dance, discover
---
spring:
  profiles: articulo
words: a, the
---
spring:
  profiles: adjetivo
words: reasonable, leaky, suspicious, ordinary, unlikely
---
spring:
  profiles: sustantivo
words: boat, book, vote, seat, backpack, partition, groundhog
---
spring:
  profiles: sustantivo-frio
words: icicle, refrigerator, blizzard, snowball
